//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LegacyRating
    {
        public int Id { get; set; }
        public System.Guid UserId { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<int> Value { get; set; }
    }
}
