//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LegacyPhoto
    {
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public System.Guid UserId { get; set; }
        public string Title { get; set; }
        public string Alt { get; set; }
        public string ContentType { get; set; }
        public byte[] Image { get; set; }
        public byte[] Thumbnail { get; set; }
        public bool IsPhotoOfTheMonth { get; set; }
        public bool IsPhotoOfTheYear { get; set; }
        public string Tags { get; set; }
    }
}
