// <auto-generated />
namespace PaD.DataContexts.PaDMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class spGetHighestRankedPhotoId : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(spGetHighestRankedPhotoId));
        
        string IMigrationMetadata.Id
        {
            get { return "201609171709269_spGetHighestRankedPhotoId"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
